Enhance `modification_api.jl`
psrenergy/PSRClassesInterface.jl pull request #116
Opened 2022-11-22 14:42 UTC by pedroripper

2022-11-22 18:25 UTC, pedroripper commented
Close #102

2022-11-22 18:55 UTC, joaquimg commented on src/modification_api.jl
> +    if ! has_relations(data, collection, index)
```suggestion
    if !has_relations(data, collection, index)
```

2022-11-22 19:54 UTC, pedroripper commented
Close #108

2022-12-07 18:36 UTC, pedroripper commented
Close #109

2022-12-14 17:51 UTC, pedroripper commented
Close #110

2023-03-03 19:22 UTC, guilhermebodin commented on src/OpenStudy/relations.jl
> +    if typeof(target_reference_id) == Vector{Int}
`isa(target_reference_id, Vector{Int})`

2023-03-16 17:01 UTC, joaquimg requested changes
Anotei duas bobeirinhas que da para resolver em poucos minutos.

Abrir o PR do tutorial que o @pedroripper ja confirmou que existe

2023-03-16 18:46 UTC, merged