Single Binary packing approach
psrenergy/PSRClassesInterface.jl pull request #64
Opened 2022-02-09 14:48 UTC by guilhermebodin

2022-02-09 14:49 UTC, guilhermebodin commented
@raphasampaio @pedromxavier @joaquimg This is an attempt on packing the .hdr and .bin in a single .bin. I had a few errors with this approach but maybe it can be useful to discuss #63

2022-02-21 21:57 UTC, guilhermebodin commented
@raphasampaio @joaquimg Acho que ja resolvi aqui.

2022-02-21 22:55 UTC, joaquimg requested changes
nice! just some tweaks needed

2022-02-21 22:55 UTC, joaquimg commented on src/OpenBinary/reader.jl
> +        seek(ioh, 0) # absolute position
Only in else?

2022-02-21 22:55 UTC, joaquimg commented on src/OpenBinary/reader.jl
> +    if !single_binary
why not for single bin?

2022-02-21 22:55 UTC, joaquimg commented on src/OpenBinary/reader.jl
> +    if single_binary
is this "if" needed?
ret.hs isnt already zero?
so `seek(ret.io, ret.hs)` works for both...

2022-02-21 22:55 UTC, joaquimg commented on src/OpenBinary/reader.jl
> +        end
```suggestion
        seek(graf.io, graf.hs)
```

2022-02-22 02:13 UTC, guilhermebodin commented on src/OpenBinary/reader.jl
> +        seek(ioh, 0) # absolute position
no need for this one actually

2022-02-23 12:46 UTC, pedromxavier commented
@guilhermebodin I've just noticed that Classic's SingleBinary uses `.dat` extension. We're currently using `.bin`:

https://github.com/psrenergy/PSRClassesInterface.jl/blob/gb/single_bin/src/OpenBinary/reader.jl#L73
https://github.com/psrenergy/PSRClassesInterface.jl/blob/gb/single_bin/src/OpenBinary/writer.jl#L140

2022-02-23 13:59 UTC, raphasampaio commented
@pedromxavier the user should be able to decide any extension that he wants, in the single binary, header+binary, and CSV modes

2022-02-23 20:11 UTC, guilhermebodin commented
@raphasampaio so what do we do, fix it at `.bin` or add more options?

2022-02-23 20:13 UTC, raphasampaio commented
It's better to fix it

2022-02-23 21:38 UTC, pedromxavier commented
@raphasampaio @guilhermebodin  It looks good to have more options. In any case `.dat` should be the default behaviour to match ClassicInterface's IO for single bin.

2022-02-24 20:35 UTC, guilhermebodin commented
Changing to .dat @pedromxavier have you tested the files against the original ones?

2022-02-25 21:01 UTC, pedromxavier commented
@raphasampaio @guilhermebodin The last commits include:
- `hs::Int` removal from header contents.
- Added `skips::Union{Nothing, Vector{Tuple{Int, Int}}}` to track file cursos skips within the header in order to consider those chunks as garbage during binary comparison. Added also a parameter `store_skips::Bool` to `OpenBinary.Reader` to activate this feature.

2022-02-25 21:01 UTC, merged